In [1]:
import tensorflow_datasets as tfds

In [2]:
import tensorflow as tf

In [3]:
mnist_data = tfds.load('fashion_mnist')

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Extraction completed...: 0 file [00:00, ? file/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/fashion_mnist/3.0.1.incompleteA41US6/fashion_mnist-train.tfrecord


  0%|          | 0/60000 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/fashion_mnist/3.0.1.incompleteA41US6/fashion_mnist-test.tfrecord


  0%|          | 0/10000 [00:00<?, ? examples/s]

Dataset fashion_mnist downloaded and prepared to /root/tensorflow_datasets/fashion_mnist/3.0.1. Subsequent calls will reuse this data.


In [4]:
type(mnist_data)

dict

In [5]:
for items in mnist_data:
  print(items)

test
train


In [8]:
type(mnist_data['train'])

tensorflow.python.data.ops.dataset_ops.PrefetchDataset

In [10]:
mnist_data_train= tfds.load('fashion_mnist',split = 'train')

In [11]:
type(mnist_data_train)

tensorflow.python.data.ops.dataset_ops.PrefetchDataset

In [14]:
for item in mnist_data_train.take(1):
  print(type(item))
  print(item.keys())
  print(item['image'])
  print(item['label'])

<class 'dict'>
dict_keys(['image', 'label'])
tf.Tensor(
[[[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 18]
  [ 77]
  [227]
  [227]
  [208]
  [210]
  [225]
  [216]
  [ 85]
  [ 32]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 61]
  [100]
  [ 97]
  [ 80]
  [ 57]
  [117]
  [227]
  [238]
  [115]
  [ 49]
  [ 78]
  [106]
  [108]
  [ 71]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 81]
  [105]
  [ 80]
  [ 69]
  [ 72]
  [ 64]
  [ 44]
  [ 21]
  [ 13]
  [ 44]
  [ 69]
  [ 75]
  [ 75]
  [ 80]
  [114]
  [ 80]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]
  [ 26]
  [ 92]
  [ 69]
  [ 68]
  [ 75]
  [ 75]
  [ 71]
  [ 74]
  [ 83]
  [ 75]
  [ 77]
  [ 78]
  [ 74]
  [ 74]
  [ 83]
  [ 77]
  [108]
  [ 34]
  [  0]
  [  0]
  [  0]
  [  0]
  [  0]]

 [[  0]
  [  0]
  [  0]
  [  0]
  [  0]


In [17]:
mnist_data_train,info = tfds.load('fashion_mnist',split= 'train',with_info='True')

In [18]:
print(info)

tfds.core.DatasetInfo(
    name='fashion_mnist',
    version=3.0.1,
    description='Fashion-MNIST is a dataset of Zalando's article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28x28 grayscale image, associated with a label from 10 classes.',
    homepage='https://github.com/zalandoresearch/fashion-mnist',
    features=FeaturesDict({
        'image': Image(shape=(28, 28, 1), dtype=tf.uint8),
        'label': ClassLabel(shape=(), dtype=tf.int64, num_classes=10),
    }),
    total_num_examples=70000,
    splits={
        'test': 10000,
        'train': 60000,
    },
    supervised_keys=('image', 'label'),
    citation="""@article{DBLP:journals/corr/abs-1708-07747,
      author    = {Han Xiao and
                   Kashif Rasul and
                   Roland Vollgraf},
      title     = {Fashion-MNIST: a Novel Image Dataset for Benchmarking Machine Learning
                   Algorithms},
      journal   = {CoRR},
      volume

In [19]:
(tr_img,tr_label),(t_img,t_label) = tfds.as_numpy(tfds.load('fashion_mnist',split = ['train','test'],batch_size = -1,as_supervised= True))

Instructions for updating:
Use `tf.data.Dataset.get_single_element()`.


Instructions for updating:
Use `tf.data.Dataset.get_single_element()`.


In [20]:
tr_img = tr_img / 255.0
t_img = t_img / 255.0
model = tf.keras.models.Sequential([
 tf.keras.layers.Flatten(input_shape=(28,28,1)),
 tf.keras.layers.Dense(128, activation=tf.nn.relu),
 tf.keras.layers.Dropout(0.2),
 tf.keras.layers.Dense(10, activation=tf.nn.softmax)
])
model.compile(optimizer='adam',
 loss='sparse_categorical_crossentropy',
 metrics=['accuracy'])
model.fit(tr_img, tr_label, epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.5259 - accuracy: 0.8134
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3999 - accuracy: 0.8551
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3661 - accuracy: 0.8665
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.3427 - accuracy: 0.8748
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3298 - accuracy: 0.8790


In [22]:
data = tfds.load('horses_or_humans',as_supervised=True,split='train')

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/horses_or_humans/3.0.0.incompleteP7K10G/horses_or_humans-train.tfrecord


  0%|          | 0/1027 [00:00<?, ? examples/s]

0 examples [00:00, ? examples/s]

Shuffling and writing examples to /root/tensorflow_datasets/horses_or_humans/3.0.0.incompleteP7K10G/horses_or_humans-test.tfrecord


  0%|          | 0/256 [00:00<?, ? examples/s]

Dataset horses_or_humans downloaded and prepared to /root/tensorflow_datasets/horses_or_humans/3.0.0. Subsequent calls will reuse this data.


In [23]:
type(data)

tensorflow.python.data.ops.dataset_ops.PrefetchDataset

In [27]:
tr_batch = data.shuffle(110).batch(10)

In [29]:
type(tr_batch) # Simply use this to pass into the model.fit step.
# Same can be done for validation, make batched and pass into model.fit(validation_data=validation_batch,validation_steps =1) /// Do provide the validation steps

tensorflow.python.data.ops.dataset_ops.BatchDataset

In [33]:
#Data Augmentation :
def augmentation(image,label):
  image = tf.cast(image,tf.float32)
  image = image/255
  image = tf.image.random_flip_left_right(image)  # Any augmentation technique can be used
  return image,label

In [31]:
data = tfds.load('fashion_mnist',split= 'train',as_supervised=True)

In [34]:
train_data = data.map(augmentation)

In [35]:
train_batch = train_data.shuffle(110).batch(10)

In [37]:
# Version Control = Major.Minor.Patch  for datasets
#MAjor: Changes the format and reordering
#Minor : Changes the additional feature
#Patches: REorganisation of data

In [38]:
pip install tensorflow-addons

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 1.1 MB 5.8 MB/s 


In [39]:
import tensorflow_addons as tfa

In [40]:
def augmentation(image,label):
  image = tf.cast(image,tf.float32)
  image = image/255
  image = tf.image.random_flip_left_right(image)  # Any augmentation technique can be used
  image = tfa.image.rotate(image,40,interpolation ="NEAREST")
  return image,label

In [41]:
#Using custom splits

In [43]:
#using split = 'key' changing into split = 'train[start:stop:step:]' or 'train[:80%]' or 'train[-1100]+train[:1000]

In [44]:
#TFrecords : file downloaded is cached and stored as TFrecords

In [51]:
file_name ='/root/tensorflow_datasets/horses_or_humans/3.0.0/horses_or_humans-test.tfrecord-00000-of-00001'

In [52]:
raw_record = tf.data.TFRecordDataset(file_name)

In [53]:
type(raw_record)

tensorflow.python.data.ops.readers.TFRecordDatasetV2

In [55]:
for record in raw_record.take(1):
  print(record)

tf.Tensor(b'\n\xc4\xc5\x02\n\xb0\xc5\x02\n\x05image\x12\xa5\xc5\x02\n\xa1\xc5\x02\n\x9d\xc5\x02\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x01,\x00\x00\x01,\x08\x06\x00\x00\x00y}\x8eu\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x00\tpHYs\x00\x00\x0e\xc4\x00\x00\x0e\xc4\x01\x95+\x0e\x1b\x00\x00 \x00IDATx\x9c\xec\xbd{\x94\xa5\xd7Y\xde\xf9\xdb{\x7f\x97s\xea\xd4\xb5\xd5\xf7\x96\xac\x96\xd4\xb2,,\xe3\x1b\x83\x03\xc6\xc0\x10[L\xb0\'\xfc\x11LX`\x9b\x0cI\x062\t\xe4\xc2\xcc\x90\x995\xc90\x97\x95IB\xfe\x89\x13\xc2\xc58\x19l\x821\x93\x95@\x0c6\x10l\xb0ec\xebf\xa9u\xb5\xdc\xb2%u\xab\xbb\xd5\xdd\xd5U]u\xae\xdfe\xef=\x7f\xbc{\x7f\xa7\xda\xc6\xd8\xc6\x17\xe9\xb4\xf7\xb3V\xab\xd5U\xa7N\x9ds\xaa\xbe\xe7\xbc\xef\xb3\x9f\xf7y\x95\xf7\xde\x93\x90\x90\x90\xb0\x00\xd0\xcf\xf7\x03HHHH\xf8R\x91\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\

In [57]:
# Create a description of the features
feature_description = {
 'image': tf.io.FixedLenFeature([], dtype=tf.string),
 'label': tf.io.FixedLenFeature([], dtype=tf.int64),
}
def _parse_function(example_proto):
 # Parse the input `tf.Example` proto using the dictionary above
 return tf.io.parse_single_example(example_proto, feature_description)
parsed_dataset = raw_record.map(_parse_function)
for parsed_record in parsed_dataset.take(1):
 print((parsed_record))  #Gives us a PNG Format

{'image': <tf.Tensor: shape=(), dtype=string, numpy=b'\x89PNG\r\n\x1a\n\x00\x00\x00\rIHDR\x00\x00\x01,\x00\x00\x01,\x08\x06\x00\x00\x00y}\x8eu\x00\x00\x00\x04sBIT\x08\x08\x08\x08|\x08d\x88\x00\x00\x00\tpHYs\x00\x00\x0e\xc4\x00\x00\x0e\xc4\x01\x95+\x0e\x1b\x00\x00 \x00IDATx\x9c\xec\xbd{\x94\xa5\xd7Y\xde\xf9\xdb{\x7f\x97s\xea\xd4\xb5\xd5\xf7\x96\xac\x96\xd4\xb2,,\xe3\x1b\x83\x03\xc6\xc0\x10[L\xb0\'\xfc\x11LX`\x9b\x0cI\x062\t\xe4\xc2\xcc\x90\x995\xc90\x97\x95IB\xfe\x89\x13\xc2\xc58\x19l\x821\x93\x95@\x0c6\x10l\xb0ec\xebf\xa9u\xb5\xdc\xb2%u\xab\xbb\xd5\xdd\xd5U]u\xae\xdfe\xef=\x7f\xbc{\x7f\xa7\xda\xc6\xd8\xc6\x17\xe9\xb4\xf7\xb3V\xab\xd5U\xa7N\x9ds\xaa\xbe\xe7\xbc\xef\xb3\x9f\xf7y\x95\xf7\xde\x93\x90\x90\x90\xb0\x00\xd0\xcf\xf7\x03HHHH\xf8R\x91\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x08+!!aa\x90\x0

In [58]:
#ETL in tensorflow

In [61]:
file_pattern =f'/root/tensorflow_datasets/horses_or_humans/3.0.0/horses_or_humans-train.tfrecord*'
files = tf.data.Dataset.list_files(file_pattern)


In [62]:
train_dataset = files.interleave(
 tf.data.TFRecordDataset,
 cycle_length=4,
 num_parallel_calls=tf.data.experimental.AUTOTUNE
 )


In [63]:
print(train_dataset)

<ParallelInterleaveDataset element_spec=TensorSpec(shape=(), dtype=tf.string, name=None)>


In [64]:
def read_tfrecord(serialized_example):
 feature_description={
 "image": tf.io.FixedLenFeature((), tf.string, ""),
 "label": tf.io.FixedLenFeature((), tf.int64, -1),
 }
 example = tf.io.parse_single_example(
 serialized_example, feature_description
 )
 image = tf.io.decode_jpeg(example['image'], channels=3)
 image = tf.cast(image, tf.float32)
 image = image / 255
 image = tf.image.resize(image, (300,300))
 return image, example['label']

In [67]:
import multiprocessing
cores = multiprocessing.cpu_count()
print(cores)
train_dataset = train_dataset.map(read_tfrecord, num_parallel_calls=cores)
train_dataset = train_dataset.cache()


2


In [68]:
train_dataset = train_dataset.shuffle(1024).batch(32)
train_dataset = train_dataset.prefetch(tf.data.experimental.AUTOTUNE)